---

- name: Install clamav packages
  yum: name={{ item }} state=installed
  with_items:
      - clamav
      - clamav-db
      - clamav-unofficial-sigs
  notify:
    - Initialize antivirus database

- name: Disable clam user login
  user: name=clam shell=/sbin/nologin

- name: Disable clam-update user login
  user: name=clam-update shell=/sbin/nologin

- name: Set permissions on antivirus database directory
  file: path=/var/lib/clamav state=directory owner=clam group=clam

- name: Set freshclam configuration
  template: src=freshclam.conf.j2
            dest=/etc/freshclam.conf 
            owner=root
            group=root
            mode=0644

- name: Daily clamav database update
  cron: name="Daily Virus DB Update"
        hour={{ clamav_official_db_update.hour }}
        minute={{ clamav_official_db_update.minute }}
        job="/usr/bin/freshclam"
        state=present

- name: Daily unofficial sig update
  cron: name="Daily Unofficial DB Update"
        hour={{ clamav_unofficial_db_update.hour }}
        minute={{ clamav_unofficial_db_update.minute }}
        job="/usr/bin/clamav-unofficial-sigs.sh 2>&1 | /usr/bin/logger -p local0.info -t clam-unofficial-sigs"
        state=present

- name: Daily clamav scan
  cron: name="Daily Virus Scan"
        hour={{ clamav_scan.hour }}
        minute={{ clamav_scan.minute }}
        job="/usr/bin/clamscan -r /  --detect-pua --exclude-dir=/sys/ --exclude-dir=/proc/ --exclude-dir=/dev/ --infected 2>&1 | /usr/bin/logger -p local0.info -t clamscan"
        state=present

#########################################
# Remove unused files and directories
#########################################

- name: Remove unused clamav log and cron files
  file: path={{ item }} state=absent
  with_items:
    - /etc/cron.d/clamav-unofficial-sigs
    - /etc/cron.hourly/freshclam
    - /var/log/clamav
    - /var/log/clamav-unofficial-sigs
    - /etc/logrotate.d/freshclam
    - /etc/logrotate.d/clamav-unofficial-sigs
