---

- name: Set ntp configuration
  template: src=ntp.conf.j2 dest=/etc/ntp.conf owner=root group=root
  notify:
    - restart ntpd
    
- name: Set iptables configuration
  copy: src=110_ntp_server dest=/etc/ferm/ferm.d/110_ntp_server owner=root group=root
